
// ForTest.h : PROJECT_NAME 应用程序的主头文件
//

#pragma once

#ifndef __AFXWIN_H__
	#error "在包含此文件之前包含“stdafx.h”以生成 PCH 文件"
#endif

#include "resource.h"		// 主符号
#include "DSCAMAPI.h"   

//////// model define ()///////////////////////////////////////////////////////////////
//#define DTCM132
//#define DTCM210
#define DTCM300
//#define DTCM500
//#define DTCM800
//#define DTCM900
////////////////// RESOLUTION SETTINGS DEFINE ///////////////////////////////////////////
//#define DTCM1000
//#define DTCM1400
////////////////// RESOLUTION SETTINGS DEFINE ///////////////////////////////////////////

#ifdef DTCM1400
#define HAVE_SPEED_SUPER  1
#define MODEL_NAME          "DTCM1400"
#define PREVIEW_RESOLUTION  R2048_1536

#define RESOLUTION_A_INDEX  R4384_3288
#define RESOLUTION_A_TEXT  "4384*3288"
#define RESOLUTION_A_ENABLE TRUE

#define RESOLUTION_B_INDEX  R2048_1536
#define RESOLUTION_B_TEXT  "2048*1536"
#define RESOLUTION_B_ENABLE TRUE

#define RESOLUTION_C_INDEX  R1280_960
#define RESOLUTION_C_TEXT  "1280*960"
#define RESOLUTION_C_ENABLE TRUE

#define RESOLUTION_D_INDEX  R1024_768
#define RESOLUTION_D_TEXT  "1024*768"
#define RESOLUTION_D_ENABLE TRUE

#define RESOLUTION_E_INDEX  R640_480
#define RESOLUTION_E_TEXT  "640*480"
#define RESOLUTION_E_ENABLE TRUE

#define RESOLUTION_F_INDEX  R_ROI
#define RESOLUTION_F_TEXT  "ROI"
#define RESOLUTION_F_ENABLE TRUE

#define ROI_HOFFSET  320
#define ROI_VOFFSET  240
#define ROI_WIDTH    1280
#define ROI_HEIGHT   1024
#endif
#ifdef DTCM1000
#define HAVE_SPEED_SUPER  1
#define MODEL_NAME          "DTCM1000"
#define PREVIEW_RESOLUTION  R3664_2748

#define RESOLUTION_A_INDEX  R3664_2748
#define RESOLUTION_A_TEXT  "3664*2748"
#define RESOLUTION_A_ENABLE TRUE

#define RESOLUTION_B_INDEX  R1600_1200
#define RESOLUTION_B_TEXT  "1600*1200"
#define RESOLUTION_B_ENABLE TRUE

#define RESOLUTION_C_INDEX  R1280_960
#define RESOLUTION_C_TEXT  "1280*960"
#define RESOLUTION_C_ENABLE TRUE

#define RESOLUTION_D_INDEX  R800_600
#define RESOLUTION_D_TEXT  "800*600"
#define RESOLUTION_D_ENABLE TRUE

#define RESOLUTION_E_INDEX  R640_480
#define RESOLUTION_E_TEXT  "640*480"
#define RESOLUTION_E_ENABLE TRUE

#define RESOLUTION_F_INDEX  R_ROI
#define RESOLUTION_F_TEXT  "ROI"
#define RESOLUTION_F_ENABLE TRUE

#define ROI_HOFFSET  320
#define ROI_VOFFSET  240
#define ROI_WIDTH    1280
#define ROI_HEIGHT   1024
#endif

#ifdef DTCM210
#define MODEL_NAME "DTCM210"
#define PREVIEW_RESOLUTION  R1024_768

#define RESOLUTION_A_INDEX  R1600_1200
#define RESOLUTION_A_TEXT  "1600*1200"	
#define RESOLUTION_A_ENABLE TRUE

#define RESOLUTION_B_INDEX  R800_600
#define RESOLUTION_B_TEXT  "800*600"	
#define RESOLUTION_B_ENABLE TRUE

#define RESOLUTION_C_INDEX  R640_480
#define RESOLUTION_C_TEXT  "640*480"	
#define RESOLUTION_C_ENABLE TRUE

#define RESOLUTION_D_INDEX  R_ROI+1
#define RESOLUTION_D_TEXT  "Not Use"	
#define RESOLUTION_D_ENABLE FALSE

#define RESOLUTION_E_INDEX  R_ROI+2
#define RESOLUTION_E_TEXT  "Not use"
#define RESOLUTION_E_ENABLE FALSE

#define RESOLUTION_F_INDEX  R_ROI
#define RESOLUTION_F_TEXT  "ROI"
#define RESOLUTION_F_ENABLE TRUE

#define ROI_HOFFSET  320
#define ROI_VOFFSET  240
#define ROI_WIDTH    1024
#define ROI_HEIGHT   768
#endif
#ifdef DTCM900
#define HAVE_SPEED_SUPER  1
#define MODEL_NAME "DTCM900"
#define PREVIEW_RESOLUTION  R1600_1200

#define RESOLUTION_A_INDEX  R3488_2616
#define RESOLUTION_A_TEXT  "3488*2616"
#define RESOLUTION_A_ENABLE TRUE

#define RESOLUTION_B_INDEX  R1600_1200
#define RESOLUTION_B_TEXT  "1600*1200"
#define RESOLUTION_B_ENABLE TRUE

#define RESOLUTION_C_INDEX  R1280_960
#define RESOLUTION_C_TEXT  "1280*960"
#define RESOLUTION_C_ENABLE TRUE

#define RESOLUTION_D_INDEX  R800_600
#define RESOLUTION_D_TEXT  "800*600"
#define RESOLUTION_D_ENABLE TRUE

#define RESOLUTION_E_INDEX  R640_480
#define RESOLUTION_E_TEXT  "640*480"
#define RESOLUTION_E_ENABLE TRUE

#define RESOLUTION_F_INDEX  R_ROI
#define RESOLUTION_F_TEXT  "ROI"
#define RESOLUTION_F_ENABLE TRUE

#define ROI_HOFFSET  320
#define ROI_VOFFSET  240
#define ROI_WIDTH    1280
#define ROI_HEIGHT   1024
#endif

#ifdef DTCM800
#define HAVE_SPEED_SUPER  1
#define MODEL_NAME "DTCM800"
#define PREVIEW_RESOLUTION  R1600_1200

#define RESOLUTION_A_INDEX  R3264_2448
#define RESOLUTION_A_TEXT  "3264*2448"
#define RESOLUTION_A_ENABLE TRUE

#define RESOLUTION_B_INDEX  R1600_1200
#define RESOLUTION_B_TEXT  "1600*1200"
#define RESOLUTION_B_ENABLE TRUE

#define RESOLUTION_C_INDEX  R1280_960
#define RESOLUTION_C_TEXT  "1280*960"
#define RESOLUTION_C_ENABLE TRUE

#define RESOLUTION_D_INDEX  R800_600
#define RESOLUTION_D_TEXT  "800*600"
#define RESOLUTION_D_ENABLE TRUE

#define RESOLUTION_E_INDEX  R640_480
#define RESOLUTION_E_TEXT  "640*480"
#define RESOLUTION_E_ENABLE TRUE

#define RESOLUTION_F_INDEX  R_ROI
#define RESOLUTION_F_TEXT  "ROI"
#define RESOLUTION_F_ENABLE TRUE

#define ROI_HOFFSET  320
#define ROI_VOFFSET  240
#define ROI_WIDTH    1280
#define ROI_HEIGHT   1024
#endif

#ifdef DTCM132
#define MODEL_NAME "DTCM132"

#define PREVIEW_RESOLUTION  R1280_1024

#define RESOLUTION_A_INDEX  R_ROI+1
#define RESOLUTION_A_TEXT  "Not use"
#define RESOLUTION_A_ENABLE FALSE

#define RESOLUTION_B_INDEX  R1280_1024
#define RESOLUTION_B_TEXT  "1280*1024"
#define RESOLUTION_B_ENABLE TRUE

#define RESOLUTION_C_INDEX  R640_480
#define RESOLUTION_C_TEXT  "640*480"
#define RESOLUTION_C_ENABLE TRUE

#define RESOLUTION_D_INDEX  R320_240
#define RESOLUTION_D_TEXT  "320*240"
#define RESOLUTION_D_ENABLE TRUE

#define RESOLUTION_E_INDEX  R_ROI+2
#define RESOLUTION_E_TEXT  "Not use"
#define RESOLUTION_E_ENABLE FALSE

#define RESOLUTION_F_INDEX  R_ROI
#define RESOLUTION_F_TEXT  "ROI"
#define RESOLUTION_F_ENABLE TRUE

#define ROI_HOFFSET  320
#define ROI_VOFFSET  240
#define ROI_WIDTH    640
#define ROI_HEIGHT   480
#endif

#ifdef DTCM300
#define MODEL_NAME "CBM300GM1"
#define PREVIEW_RESOLUTION  R1024_768

#define RESOLUTION_A_INDEX  R2048_1536
#define RESOLUTION_A_TEXT  "2048*1536"	
#define RESOLUTION_A_ENABLE TRUE

#define RESOLUTION_B_INDEX  R1024_768
#define RESOLUTION_B_TEXT  "1024*768"	
#define RESOLUTION_B_ENABLE TRUE

#define RESOLUTION_C_INDEX  R640_480
#define RESOLUTION_C_TEXT  "640*480"	
#define RESOLUTION_C_ENABLE TRUE

#define RESOLUTION_D_INDEX  R_ROI+1
#define RESOLUTION_D_TEXT  "Not Use"	
#define RESOLUTION_D_ENABLE FALSE

#define RESOLUTION_E_INDEX  R_ROI+2
#define RESOLUTION_E_TEXT  "Not use"
#define RESOLUTION_E_ENABLE FALSE

#define RESOLUTION_F_INDEX  R_ROI
#define RESOLUTION_F_TEXT  "ROI"
#define RESOLUTION_F_ENABLE TRUE

#define ROI_HOFFSET  640
#define ROI_VOFFSET  480
#define ROI_WIDTH    1024
#define ROI_HEIGHT   768
#endif

//"DTCM500"
#ifdef DTCM500
#define HAVE_SPEED_SUPER  1
#define MODEL_NAME "DTCM500"
#define PREVIEW_RESOLUTION  R1280_960

#define RESOLUTION_A_INDEX  R2592_1944
#define RESOLUTION_A_TEXT  "2592*1944"
#define RESOLUTION_A_ENABLE TRUE

#define RESOLUTION_B_INDEX  R1280_960
#define RESOLUTION_B_TEXT  "1280*960"
#define RESOLUTION_B_ENABLE TRUE

#define RESOLUTION_C_INDEX  R1024_768
#define RESOLUTION_C_TEXT  "1024*768"
#define RESOLUTION_C_ENABLE TRUE

#define RESOLUTION_D_INDEX  R640_480
#define RESOLUTION_D_TEXT  "640*480"
#define RESOLUTION_D_ENABLE TRUE

#define RESOLUTION_E_INDEX  R_ROI+1
#define RESOLUTION_E_TEXT  "Not use"
#define RESOLUTION_E_ENABLE FALSE

#define RESOLUTION_F_INDEX  R_ROI
#define RESOLUTION_F_TEXT  "ROI"
#define RESOLUTION_F_ENABLE TRUE

#define ROI_HOFFSET  640
#define ROI_VOFFSET  480
#define ROI_WIDTH    1280
#define ROI_HEIGHT   1024
#endif



// CForTestApp:
// 有关此类的实现，请参阅 ForTest.cpp
//

class CForTestApp : public CWinApp
{
public:
	CForTestApp();

// 重写
public:
	virtual BOOL InitInstance();

// 实现

	DECLARE_MESSAGE_MAP()
};

extern CForTestApp theApp;